### ISSUE TITLE
Dark light background needs to be less transparent

### ISSUE THREAD

**Issue by stevewhocodes** [steveWhoCodes/Modal#1]
Dark light background needs to be less transparent

**Comment by abitsalihu** [comment]
Can you give more content to which background? And I would love to help with this!

**Comment by stevewhocodes** [comment]
> Can you give more content to which background? And I would love to help with this!

I appreciate that.  I'm good.  I am just working through a GitHub tutorial on creating issues and applying labels.  Have a good day.
